author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /test
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://readux.ecds.emory.edu/books/emory:bmst8/pages/emory:gt22m/single-page/
image_size:
  page:
    height: 1000
    width: 658
  small-thumbnail:
    height: 100
    width: 65
  thumbnail:
    height: 300
    width: 197
permalink: pretty
publication_info:
  author: Luiken, Jan, 1649-1712.
  date: '2017'
  editors:
  - Sara Palmer
  tei_xml: tei.xml
  title: De onwaardige wereld  vertoond in vyftig zinnebeelden, met godlyke spreuken
    en stichtelyke verzen , an annotated digital edition
show_annotation_author: true
source_info:
  author: Luiken, Jan, 1649-1712.
  date: '1710'
  pdf_url: https://readux.ecds.emory.edu/books/emory:bmst8/pdf/#page=2
  title: 'De onwaardige wereld  vertoond in vyftig zinnebeelden, met godlyke spreuken
    en stichtelyke verzen '
  url: https://readux.ecds.emory.edu/books/emory:bmst8/
  via_readux: true
tagline: ', an annotated digital edition'
title: 'De onwaardige wereld  vertoond in vyftig zinnebeelden, met godlyke spreuken
  en stichtelyke verzen '
url: https://sarepal.github.io
version: 0.7
